### PR TITLE
Add tests for some more edge cases

### PR DESCRIPTION
**Pull request by dorianim**
Thank you very much for this repo!
I added some parameters for some potential edge cases :)

### CODE REVIEW

**Review by LadnerJonas — CHANGES_REQUESTED** [review]
Please remove all comments in this test as they help finding the correct solution. Otherwise looks great :+1:

**Review by LadnerJonas — APPROVED** [review]

**Comment by LadnerJonas** [comment]
Thanks for your Contribution! @dorianim :medal_sports: 

This test cases seems like a great addition. But please fix the requested changes, even if some are created by others.

**Comment by dorianim** [comment]
No problem, comments removed.

**Comment by LadnerJonas** [comment]
Great job! :+1:

**Pull request merged**
